# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rocky DNS Setting Test
email: sangrakl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Rocky Lee's First DNS Setting Test on AWS.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rockyleekr.com" # the base hostname & protocol for your site
twitter_username: Rocky
github_username:  Rocky

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker